version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - express

  react:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - '3000'

  express:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - '5001'