name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository_owner }}/echo-frontend ./frontend
          docker build -t ghcr.io/${{ github.repository_owner }}/echo-backend ./backend
          docker build -t ghcr.io/${{ github.repository_owner }}/echo-nginx ./nginx
          docker push ghcr.io/${{ github.repository_owner }}/echo-frontend
          docker push ghcr.io/${{ github.repository_owner }}/echo-backend
          docker push ghcr.io/${{ github.repository_owner }}/echo-nginx

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$HOST '
            docker pull ghcr.io/${{ github.repository_owner }}/echo-frontend
            docker pull ghcr.io/${{ github.repository_owner }}/echo-backend
            docker pull ghcr.io/${{ github.repository_owner }}/echo-nginx
            docker-compose up -d
          '
